### PR TITLE
Adding en to avoid error with small sentences and calling get_result before processing result

### PR DESCRIPTION
**Pull request by upkarlidder**

### CODE REVIEW

**Comment by upkarlidder** [comment]
Not sure why it added commits closed in previous PR 👎. Should I create another PR ?

**Review by sanjeevghimire — APPROVED** [review]

**Review by sanjeevghimire — APPROVED** [review]
LGTM. Will test the branch out before merge.

**Comment by sanjeevghimire** [comment]
@lidderupk I do remember removing the changes that you have currently in the PR as it was not working with the version of Watson SDK available in the cloud function. If this is working for you, I will test your branch before the merge

**Comment by upkarlidder** [comment]
@sanjeevghimire, I am using the latest. I got the NLU URL from the service dashboard. If I just clone the repo, change the param.json file and run it, I get the errors. Are you able to reproduce ? I also created two issues with more details of the errors I see.

**Comment by sanjeevghimire** [comment]
@lidderupk did you test this locally or on the cloud? I am going to test it on the cloud and see if I can reproduce the issues.

**Comment by upkarlidder** [comment]
@sanjeevghimire, I tested on IBM Cloud Functions using the commands listed in the repo. I created the NLU and visual recognition services. Visual Recognition worked fine. I got the errors in the NLU part.

**Comment by sanjeevghimire** [comment]
#23 fixes this.

**Pull request closed without merging**
